course_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('contact/', views.contact_us, name='contact'),
    path('profile/', views.profile, name='profile'),
    path('setting/', views.setting, name='setting'),
    path('panel/', views.panel, name='panel'),
    path('course/add', views.add_course, name='add_course'),
    path('course/all', views.AllCoursesView.as_view(), name='all_course')
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    GENDERS = (
        ('M', 'مرد'),
        ('F', 'زن'),
        ('U', 'هیچکدام')
    )
    gender = models.CharField(max_length=20, choices=GENDERS)
    biography = models.CharField(max_length=200)


class Course(models.Model):
    name = models.CharField(max_length=30)
    department = models.CharField(max_length=20)
    course_number = models.IntegerField()
    group_number = models.IntegerField()
    teacher = models.CharField(max_length=100)
    start_time = models.TimeField()
    end_time = models.TimeField()
    WEEKDAYS = (
        ('شنبه','شنبه'),
        ('یکشنبه','یکشنبه'),
        ('دوشنبه','دوشنبه'),
        ('سه شنبه','سه شنبه'),
        ('چهارشنبه','چهارشنبه')
    )
    first_day = models.CharField(max_length=10, choices=WEEKDAYS, null=False, blank=False)
    second_day = models.CharField(max_length=10, null=True, blank=True, choices=WEEKDAYS)

    def __str__(self):
        return self.name

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, RegexValidator
from .models import Course, UserProfileInfo


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        new = User.objects.filter(username=username)
        if new.count():
            raise forms.ValidationError("کاربری با این نام کاربری وجود دارد")
        return username

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("رمز عبور تکرار شده مطابقت ندارد")
        return password2


class ContactUsForm(forms.Form):
    subject = forms.CharField(label='عنوان', required=True)
    email = forms.EmailField(label='ایمیل', required=True)
    text = forms.CharField(label='متن', min_length=10, max_length=250, widget=forms.Textarea)


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name")


class ProfileChangeInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        exclude = ('user',)
        labels = {
            'gender': 'جنسیت',
            'biography': 'بیوگرافی'
        }
        widgets = {
            'biography': forms.Textarea()
        }

class CourseCreationForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        labels = {
            'name': 'نام درس',
            'department': 'دانشکده',
            'course_number': 'شماره درس',
            'group_number': 'شماره گروه',
            'teacher': 'استاد درس',
            'start_time': 'ساعت شروع',
            'end_time': 'ساعت پایان',
            'first_day': 'روز اول',
            'second_day': 'روز دوم'
        }
        widgets = {
            'start_time': forms.TimeInput(format='%H:%M'),
            'end_time': forms.TimeInput(format='%H:%M')
        }

polls/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .forms import RegisterForm, ContactUsForm, ProfileChangeForm, CourseCreationForm, ProfileChangeInfoForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect
from django.views import generic
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .models import Course, UserProfileInfo
from django.core.mail import send_mail


def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render(request=request))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            request.user.userprofileinfo = UserProfileInfo()
            request.user.userprofileinfo.save()
            request.user.save()
        else:
            template = loader.get_template('register.html')
            return HttpResponse(template.render({'form': form}, request=request))
    template = loader.get_template('register.html')
    return HttpResponse(template.render({'form': RegisterForm()}, request=request))


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request=request, user=user)
                return redirect('polls:index')
        else:
            template = loader.get_template('login.html')
            return HttpResponse(template.render({'form': form}, request=request))
    template = loader.get_template('login.html')
    return HttpResponse(template.render({'form': AuthenticationForm()}, request=request))


def logout_view(request):
    logout(request=request)
    return redirect('polls:index')


def contact_us(request):
    template = loader.get_template('contact.html')
    if request.method == 'POST':
        form = ContactUsForm(data=request.POST)
        if form.is_valid():
            send_mail(
                form.cleaned_data['subject'],
                form.cleaned_data['email'] + '\n' + form.cleaned_data['text'],
                'r4heidari@gmail.com',
                ['r4heidari@gmail.com']
            )
            return HttpResponse(template.render({'form': form, 'done': True}, request=request))
        else:
            return HttpResponse(template.render({'form': form, 'done': False}, request=request))
    return HttpResponse(template.render({'form': ContactUsForm(), 'done': False}, request=request))


@login_required(login_url='polls:login')
def profile(request):
    template = loader.get_template('profile.html')
    user = get_object_or_404(User, id=request.user.id)
    return HttpResponse(template.render({'user': user}, request=request))


@login_required(login_url='polls:login')
def setting(request):
    template = loader.get_template('setting.html')
    if request.method == 'POST':
        form = ProfileChangeForm(data=request.POST)
        second_form = ProfileChangeInfoForm(data=request.POST)
        if form.is_valid() and second_form.is_valid():
            if form.cleaned_data['first_name'] != '':
                request.user.first_name = form.cleaned_data['first_name']
            if form.cleaned_data['last_name'] != '':
                request.user.last_name = form.cleaned_data['last_name']
            request.user.userprofileinfo.gender = second_form.cleaned_data['gender']
            request.user.userprofileinfo.biography = second_form.cleaned_data['biography']
            request.user.userprofileinfo.save()
            request.user.save()
            return redirect('polls:profile')
        else:
            return HttpResponse(template.render({'form': form, 'second_form': second_form}, request=request))
    return HttpResponse(template.render({'form': ProfileChangeForm(), 'second_form': ProfileChangeInfoForm(
        initial={'gender': request.user.userprofileinfo.gender, 'biography': request.user.userprofileinfo.biography})},
                                        request=request))


@login_required(login_url='polls:login')
def panel(request):
    template = loader.get_template('panel.html')
    return HttpResponse(template.render(request=request))


@user_passes_test(lambda u: u.is_superuser, login_url='polls:panel')
def add_course(request):
    template = loader.get_template('add_course.html')
    if request.method == 'POST':
        form = CourseCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('polls:panel')
        else:
            return HttpResponse(template.render({'form': form}, request=request))
    return HttpResponse(template.render({'form': CourseCreationForm()}, request=request))


class AllCoursesView(generic.ListView):
    model = Course
    template_name = 'all_courses.html'

polls/templates/add_course.html
{% extends 'base.html' %}
{% block body %}
    <strong>{{ form.errors }}</strong>
    <form action="{% url 'polls:add_course' %}" method = "post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="افزودن درس">
    </form>
{% endblock %}

polls/templates/all_courses.html
{% extends 'base.html' %}
{% block body %}
    <div id="all_course">
    {% for course in course_list %}
        <div class="{{ course.course_number }}_{{ course.group_number }}">
            <h2>{{ course.name }}</h2>
            <h3>{{ course.department }}</h3>
            <h3>{{ course.start_time }} تا {{ course.end_time }}</h3>
            <h3>{{ course.first_day }}{% if course.second_day is not None %} و {{ course.second_day }}{% endif %}</h3>
        </div>
        <br>
    {% endfor %}
    </div>
{% endblock %}

polls/templates/base.html
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title>Course</title>
    {% load static %}
    <link href='{% static "/polls/style.css" %}' rel='stylesheet' type='text/css'>
</head>
<body>
    <nav class="navbar">
        <ul>
			<li><a href="{% url 'polls:index' %}">صفحه اصلی</a></li>
            {% if not request.user.is_authenticated %}
                <li><a href="{% url 'polls:register' %}">ثبت نام</a></li>
                <li><a href="{% url 'polls:login' %}">ورود</a></li>
            {% else %}
                <li><a href="{% url 'polls:profile' %}">نمایه</a></li>
                <li><a href="{% url 'polls:panel' %}">پنل</a></li>
                <li><a href="{% url 'polls:logout' %}">خروج</a></li>
            {% endif %}
            <li><a href="{% url 'polls:contact' %}">تماس با ما</a></li>
		</ul>
	</nav>
    {% block body %}

    {% endblock %}
</body>
</html>

polls/templates/contact.html
{% extends 'base.html' %}
{% block body %}
    <strong>{{ form.errors }}</strong>
    {% if not done %}
        <form action="{% url 'polls:contact' %}" method = "post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="ثبت درخواست">
        </form>
    {% else %}
        <h1>درخواست شما ثبت شد</h1>
    {% endif %}
{% endblock %}

polls/templates/index.html
{% extends 'base.html' %}
{% block body %}
    <h1>سلام به سامانه انتخاب واحد مجازی خوش آمدید</h1>
{% endblock %}

polls/templates/login.html
{% extends 'base.html' %}
{% block body %}
    <strong>{{ form.errors }}</strong>
    <form action="{% url 'polls:login' %}" method = "post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ورود">
    </form>
{% endblock %}

polls/templates/panel.html
{% extends 'base.html' %}
{% block body %}
    {% if request.user.is_superuser %}
    <h1><a href="{% url 'polls:add_course' %}">افزودن درس</a> </h1>
    {% endif %}
    <h1><a href="{% url 'polls:all_course' %}"> مشاهده درس ها</a> </h1>
{% endblock %}

polls/templates/profile.html
{% extends 'base.html' %}
{% block body %}
    <strong>{{ form.errors }}</strong>
    <div>
        <label for="text_first_name"><b>نام:</b></label>
        <span id="text_first_name">{{ user.first_name }}</span>
        <br>
        <label for="text_last_name"><b>نام خانوادگی:</b></label>
        <span id="text_last_name">{{ user.last_name }}</span>
        <br>
        <label for="text_username"><b>نام کاربری:</b></label>
        <span id="text_username">{{ user.username }}</span>
        <br>
        <label for="text_username"><b>بیوگرافی:</b></label>
        <span id="text_username">{{ user.userprofileinfo.biography }}</span>
        <br>
        <label for="text_username"><b>جنسیت:</b></label>
        <span id="text_username">{{ user.userprofileinfo.gender }}</span>
    </div>
    <p><a href="{% url 'polls:setting' %}">ویرایش پروفایل</a> </p>
{% endblock %}

polls/templates/register.html
{% extends 'base.html' %}
{% block body %}
    <strong>{{ form.errors }}</strong>
    <form action="{% url 'polls:register' %}" method = "post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ثبت نام">
    </form>
{% endblock %}

polls/templates/setting.html
{% extends 'base.html' %}
{% block body %}
    <strong>{{ form.errors }}</strong>
    <form action="{% url 'polls:setting' %}" method = "post">{% csrf_token %}
        {{ form.as_p }}
        {{ second_form.as_p }}
        <input type="submit" value="ویرایش">
    </form>
{% endblock %}